/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol

// Source: sanity/extract.json
export type SeasonReference = {
  _ref: string
  _type: "reference"
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: "season"
}

export type FieldReference = {
  _ref: string
  _type: "reference"
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: "field"
}

export type AgronomyRecommendation = {
  _id: string
  _type: "agronomyRecommendation"
  _createdAt: string
  _updatedAt: string
  _rev: string
  season?: SeasonReference
  field?: FieldReference
  type?: "scout_pest" | "monitor" | "review_benchmark" | "review_data" | "custom"
  status?: "proposed" | "approved" | "rejected" | "completed" | "expired"
  rationale?: string
  evidence?: Array<{
    kind?: string
    label?: string
    ref?: string
    detail?: string
    _type: "evidenceItem"
    _key: string
  }>
  createdAt?: string
  createdBy?: string
  reviewedAt?: string
  reviewedBy?: string
  decisionNote?: string
  expiresAt?: string
}

export type CropReference = {
  _ref: string
  _type: "reference"
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: "crop"
}

export type Benchmark = {
  _id: string
  _type: "benchmark"
  _createdAt: string
  _updatedAt: string
  _rev: string
  source?: "psd" | "harveststat" | "worldbank"
  scope?: "national" | "provincial"
  region?: string
  commodity?: string
  crop?: CropReference
  unit?: string
  observations?: Array<{
    year?: number
    value?: number
    _type: "observation"
    _key: string
  }>
  sourceUrl?: string
  licence?: string
  retrievedAt?: string
}

export type WeatherSnapshot = {
  _id: string
  _type: "weatherSnapshot"
  _createdAt: string
  _updatedAt: string
  _rev: string
  field?: FieldReference
  season?: SeasonReference
  fetchedAt?: string
  triggeredBy?: string
  forecastDays?: number
  data?: string
  summary?: {
    avgTempMax?: number
    avgTempMin?: number
    totalPrecipitation?: number
    avgSoilTemp?: number
    avgSoilMoisture?: number
    totalET0?: number
  }
  period?: {
    start?: string
    end?: string
  }
}

export type SanityImageAssetReference = {
  _ref: string
  _type: "reference"
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset"
}

export type Observation = {
  _id: string
  _type: "observation"
  _createdAt: string
  _updatedAt: string
  _rev: string
  field?: FieldReference
  season?: SeasonReference
  date?: string
  notes?: string
  images?: Array<{
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: "image"
    _key: string
  }>
  tags?: Array<string>
}

export type SanityImageCrop = {
  _type: "sanity.imageCrop"
  top?: number
  bottom?: number
  left?: number
  right?: number
}

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot"
  x?: number
  y?: number
  height?: number
  width?: number
}

export type PestReport = {
  _id: string
  _type: "pestReport"
  _createdAt: string
  _updatedAt: string
  _rev: string
  field?: FieldReference
  season?: SeasonReference
  date?: string
  source?: "gbif" | "manual"
  sourceId?: string
  sourceUrl?: string
  distanceKm?: number
  scope?: "regional" | "field"
  severityBasis?: string
  pest?: string
  severity?: "low" | "medium" | "high" | "critical"
  affectedArea?: string
  images?: Array<{
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: "image"
    _key: string
  }>
  recommendedAction?: string
  resolved?: boolean
  resolutionNotes?: string
}

export type Treatment = {
  _id: string
  _type: "treatment"
  _createdAt: string
  _updatedAt: string
  _rev: string
  season?: SeasonReference
  date?: string
  type?: "fertiliser" | "pesticide" | "herbicide" | "fungicide" | "irrigation" | "other"
  product?: string
  dosage?: string
  method?: "broadcast" | "foliar" | "drip" | "spray" | "injection"
  applicator?: string
  notes?: string
}

export type Season = {
  _id: string
  _type: "season"
  _createdAt: string
  _updatedAt: string
  _rev: string
  field?: FieldReference
  crop?: CropReference
  year?: number
  plantingDate?: string
  expectedHarvest?: string
  actualHarvest?: string
  derivedMaturityDate?: string
  stage?: "planning" | "planted" | "growing" | "pre-harvest" | "harvested" | "review"
  stageHistory?: Array<{
    stage?: string
    previousStage?: string
    effectiveDate?: string
    timestamp?: string
    basis?: string
    gddTotal?: number
    derivedFrom?: "plantingDate" | "gdd-model" | "regional-benchmark"
    triggeredBy?: string
    notes?: string
    weatherFetched?: boolean
    weatherSnapshotId?: string
    _type: "stageChange"
    _key: string
  }>
  yieldAmount?: number
  yieldNotes?: string
}

export type Crop = {
  _id: string
  _type: "crop"
  _createdAt: string
  _updatedAt: string
  _rev: string
  name?: string
  species?: string
  cultivar?: string
  gddModelKey?: "wheat" | "canola" | "narrow-leafed lupin"
  growthCycleDays?: number
  category?: "grain" | "oilseed" | "legume" | "fruit" | "vegetable" | "pasture" | "other"
  benchmarks?: {
    psdCommodityCode?: string
    harvestStatProduct?: string
    worldBankIndicator?: string
    unavailableReason?: string
  }
  pestWatch?: Array<{
    pest?: string
    gbifTaxonKey?: number
    _type: "pestWatchItem"
    _key: string
  }>
  notes?: string
}

export type FarmReference = {
  _ref: string
  _type: "reference"
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: "farm"
}

export type Field = {
  _id: string
  _type: "field"
  _createdAt: string
  _updatedAt: string
  _rev: string
  name?: string
  slug?: Slug
  farm?: FarmReference
  coordinates?: Geopoint
  hectares?: number
  soilType?: "sandy" | "loamy" | "clay" | "silty" | "peaty" | "chalky"
  colour?: string
  notes?: string
}

export type Geopoint = {
  _type: "geopoint"
  lat?: number
  lng?: number
  alt?: number
}

export type Slug = {
  _type: "slug"
  current?: string
  source?: string
}

export type Farm = {
  _id: string
  _type: "farm"
  _createdAt: string
  _updatedAt: string
  _rev: string
  name?: string
  slug?: Slug
  location?: string
  coordinates?: Geopoint
  description?: string
}

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch"
  background?: string
  foreground?: string
  population?: number
  title?: string
}

export type SanityImagePalette = {
  _type: "sanity.imagePalette"
  darkMuted?: SanityImagePaletteSwatch
  lightVibrant?: SanityImagePaletteSwatch
  darkVibrant?: SanityImagePaletteSwatch
  vibrant?: SanityImagePaletteSwatch
  dominant?: SanityImagePaletteSwatch
  lightMuted?: SanityImagePaletteSwatch
  muted?: SanityImagePaletteSwatch
}

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions"
  height?: number
  width?: number
  aspectRatio?: number
}

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata"
  location?: Geopoint
  dimensions?: SanityImageDimensions
  palette?: SanityImagePalette
  lqip?: string
  blurHash?: string
  thumbHash?: string
  hasAlpha?: boolean
  isOpaque?: boolean
}

export type SanityFileAsset = {
  _id: string
  _type: "sanity.fileAsset"
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  source?: SanityAssetSourceData
}

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData"
  name?: string
  id?: string
  url?: string
}

export type SanityImageAsset = {
  _id: string
  _type: "sanity.imageAsset"
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  metadata?: SanityImageMetadata
  source?: SanityAssetSourceData
}

export type AllSanitySchemaTypes =
  | SeasonReference
  | FieldReference
  | AgronomyRecommendation
  | CropReference
  | Benchmark
  | WeatherSnapshot
  | SanityImageAssetReference
  | Observation
  | SanityImageCrop
  | SanityImageHotspot
  | PestReport
  | Treatment
  | Season
  | Crop
  | FarmReference
  | Field
  | Geopoint
  | Slug
  | Farm
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
