/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol

// Source: sanity/extract.json
export type RegionGrid = {
  _id: string
  _type: "regionGrid"
  _createdAt: string
  _updatedAt: string
  _rev: string
  seasonStart?: string
  throughDate?: string
  archiveUpdatedAt?: string
  forecastAt?: string
  lastAttemptAt?: string
  lastError?: string
  cells?: Array<{
    lat?: number
    lng?: number
    land?: boolean
    gdd?: number
    tempMax?: number
    rain7?: number
    _type: "regionCell"
    _key: string
  }>
}

export type SeasonReference = {
  _ref: string
  _type: "reference"
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: "season"
}

export type FieldReference = {
  _ref: string
  _type: "reference"
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: "field"
}

export type AgronomyRecommendation = {
  _id: string
  _type: "agronomyRecommendation"
  _createdAt: string
  _updatedAt: string
  _rev: string
  season?: SeasonReference
  field?: FieldReference
  type?: "scout_pest" | "monitor" | "review_benchmark" | "review_data" | "custom"
  status?: "proposed" | "approved" | "rejected" | "completed" | "expired"
  rationale?: string
  evidence?: Array<{
    kind?: string
    label?: string
    ref?: string
    detail?: string
    _type: "evidenceItem"
    _key: string
  }>
  createdAt?: string
  createdBy?: string
  reviewedAt?: string
  reviewedBy?: string
  decisionNote?: string
  expiresAt?: string
}

export type CropReference = {
  _ref: string
  _type: "reference"
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: "crop"
}

export type Benchmark = {
  _id: string
  _type: "benchmark"
  _createdAt: string
  _updatedAt: string
  _rev: string
  source?: "psd" | "harveststat" | "worldbank"
  scope?: "national" | "provincial"
  region?: string
  commodity?: string
  crop?: CropReference
  unit?: string
  observations?: Array<{
    year?: number
    value?: number
    _type: "observation"
    _key: string
  }>
  sourceUrl?: string
  licence?: string
  retrievedAt?: string
}

export type WeatherSnapshot = {
  _id: string
  _type: "weatherSnapshot"
  _createdAt: string
  _updatedAt: string
  _rev: string
  field?: FieldReference
  season?: SeasonReference
  fetchedAt?: string
  triggeredBy?: string
  forecastDays?: number
  data?: string
  summary?: {
    avgTempMax?: number
    avgTempMin?: number
    totalPrecipitation?: number
    avgSoilTemp?: number
    avgSoilMoisture?: number
    totalET0?: number
  }
  period?: {
    start?: string
    end?: string
  }
}

export type SanityImageAssetReference = {
  _ref: string
  _type: "reference"
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset"
}

export type Observation = {
  _id: string
  _type: "observation"
  _createdAt: string
  _updatedAt: string
  _rev: string
  field?: FieldReference
  season?: SeasonReference
  date?: string
  notes?: string
  images?: Array<{
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: "image"
    _key: string
  }>
  tags?: Array<string>
}

export type SanityImageCrop = {
  _type: "sanity.imageCrop"
  top?: number
  bottom?: number
  left?: number
  right?: number
}

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot"
  x?: number
  y?: number
  height?: number
  width?: number
}

export type PestReport = {
  _id: string
  _type: "pestReport"
  _createdAt: string
  _updatedAt: string
  _rev: string
  field?: FieldReference
  season?: SeasonReference
  date?: string
  source?: "gbif" | "manual"
  sourceId?: string
  sourceUrl?: string
  distanceKm?: number
  scope?: "regional" | "field"
  severityBasis?: string
  pest?: string
  severity?: "low" | "medium" | "high" | "critical"
  affectedArea?: string
  images?: Array<{
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: "image"
    _key: string
  }>
  recommendedAction?: string
  resolved?: boolean
  resolutionNotes?: string
}

export type Treatment = {
  _id: string
  _type: "treatment"
  _createdAt: string
  _updatedAt: string
  _rev: string
  season?: SeasonReference
  date?: string
  type?: "fertiliser" | "pesticide" | "herbicide" | "fungicide" | "irrigation" | "other"
  product?: string
  dosage?: string
  method?: "broadcast" | "foliar" | "drip" | "spray" | "injection"
  applicator?: string
  notes?: string
}

export type Season = {
  _id: string
  _type: "season"
  _createdAt: string
  _updatedAt: string
  _rev: string
  field?: FieldReference
  crop?: CropReference
  year?: number
  plantingDate?: string
  expectedHarvest?: string
  actualHarvest?: string
  derivedMaturityDate?: string
  stage?: "planning" | "planted" | "growing" | "pre-harvest" | "harvested" | "review"
  stageHistory?: Array<{
    stage?: string
    previousStage?: string
    effectiveDate?: string
    timestamp?: string
    basis?: string
    gddTotal?: number
    derivedFrom?: "plantingDate" | "gdd-model" | "regional-benchmark"
    triggeredBy?: string
    notes?: string
    weatherFetched?: boolean
    weatherSnapshotId?: string
    _type: "stageChange"
    _key: string
  }>
  yieldAmount?: number
  yieldNotes?: string
  aiSummary?: {
    text?: string
    generatedAt?: string
  }
  notes?: Array<{
    createdAt?: string
    updatedAt?: string
    author?: string
    ownerId?: string
    body?: Array<{
      children?: Array<{
        marks?: Array<string>
        text?: string
        _type: "span"
        _key: string
      }>
      style?: "normal"
      listItem?: "bullet"
      markDefs?: null
      level?: number
      _type: "block"
      _key: string
    }>
    _type: "seasonNote"
    _key: string
  }>
}

export type Crop = {
  _id: string
  _type: "crop"
  _createdAt: string
  _updatedAt: string
  _rev: string
  name?: string
  species?: string
  cultivar?: string
  category?: "grain" | "oilseed" | "legume" | "fruit" | "vegetable" | "pasture" | "other"
  gddModelKey?: "wheat" | "canola" | "narrow-leafed lupin"
  growthCycleDays?: number
  benchmarks?: {
    psdCommodityCode?: string
    harvestStatProduct?: string
    worldBankIndicator?: string
    unavailableReason?: string
  }
  pestWatch?: Array<{
    pest?: string
    gbifTaxonKey?: number
    _type: "pestWatchItem"
    _key: string
  }>
  notes?: string
}

export type FarmReference = {
  _ref: string
  _type: "reference"
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: "farm"
}

export type SanityFileAssetReference = {
  _ref: string
  _type: "reference"
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: "sanity.fileAsset"
}

export type Field = {
  _id: string
  _type: "field"
  _createdAt: string
  _updatedAt: string
  _rev: string
  name?: string
  slug?: Slug
  farm?: FarmReference
  coordinates?: Geopoint
  hectares?: number
  soilType?: "sandy" | "loamy" | "clay" | "silty" | "peaty" | "chalky"
  colour?: string
  notes?: string
  photo?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: "image"
  }
  soilReport?: {
    asset?: SanityFileAssetReference
    media?: unknown
    _type: "file"
  }
}

export type Geopoint = {
  _type: "geopoint"
  lat?: number
  lng?: number
  alt?: number
}

export type Slug = {
  _type: "slug"
  current?: string
  source?: string
}

export type Farm = {
  _id: string
  _type: "farm"
  _createdAt: string
  _updatedAt: string
  _rev: string
  name?: string
  slug?: Slug
  location?: string
  coordinates?: Geopoint
  description?: string
}

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch"
  background?: string
  foreground?: string
  population?: number
  title?: string
}

export type SanityImagePalette = {
  _type: "sanity.imagePalette"
  darkMuted?: SanityImagePaletteSwatch
  lightVibrant?: SanityImagePaletteSwatch
  darkVibrant?: SanityImagePaletteSwatch
  vibrant?: SanityImagePaletteSwatch
  dominant?: SanityImagePaletteSwatch
  lightMuted?: SanityImagePaletteSwatch
  muted?: SanityImagePaletteSwatch
}

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions"
  height?: number
  width?: number
  aspectRatio?: number
}

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata"
  location?: Geopoint
  dimensions?: SanityImageDimensions
  palette?: SanityImagePalette
  lqip?: string
  blurHash?: string
  thumbHash?: string
  hasAlpha?: boolean
  isOpaque?: boolean
}

export type SanityFileAsset = {
  _id: string
  _type: "sanity.fileAsset"
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  source?: SanityAssetSourceData
}

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData"
  name?: string
  id?: string
  url?: string
}

export type SanityImageAsset = {
  _id: string
  _type: "sanity.imageAsset"
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  metadata?: SanityImageMetadata
  source?: SanityAssetSourceData
}

export type AllSanitySchemaTypes =
  | RegionGrid
  | SeasonReference
  | FieldReference
  | AgronomyRecommendation
  | CropReference
  | Benchmark
  | WeatherSnapshot
  | SanityImageAssetReference
  | Observation
  | SanityImageCrop
  | SanityImageHotspot
  | PestReport
  | Treatment
  | Season
  | Crop
  | FarmReference
  | SanityFileAssetReference
  | Field
  | Geopoint
  | Slug
  | Farm
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset

// Source: src/lib/sanity/queries.ts
// Variable: LOAD_FARMS_QUERY
// Query: *[_type == "farm" && defined(slug.current)] | order(name asc){  _id, name, "slug": slug.current, location,  "coordinates": coordinates{lat, lng},  "fieldCount": count(*[_type == "field" && farm._ref == ^._id]),  "hectares": math::sum(*[_type == "field" && farm._ref == ^._id].hectares),  "activeSeasons": count(*[_type == "season" && stage != "review" && field->farm._ref == ^._id])}
export type LOAD_FARMS_QUERY_RESULT = Array<{
  _id: string
  name: string | null
  slug: string | null
  location: string | null
  coordinates: {
    lat: number | null
    lng: number | null
  } | null
  fieldCount: number
  hectares: number
  activeSeasons: number
}>

// Source: src/lib/sanity/queries.ts
// Variable: LOAD_FARM_OVERVIEW_FARM_QUERY
// Query: *[_type == "farm" && slug.current == $slug][0]{  name, "slug": slug.current, location, "coordinates": coordinates{lat, lng}}
export type LOAD_FARM_OVERVIEW_FARM_QUERY_RESULT = {
  name: string | null
  slug: string | null
  location: string | null
  coordinates: {
    lat: number | null
    lng: number | null
  } | null
} | null

// Source: src/lib/sanity/queries.ts
// Variable: LOAD_FARM_OVERVIEW_FIELDS_QUERY
// Query: *[_type == "field" && farm->slug.current == $slug] | order(name asc){  _id, name, hectares, soilType, colour,  "photo": photo{hotspot, crop, "asset": asset->{_id, "lqip": metadata.lqip, "dominant": metadata.palette.dominant.background}},  "coordinates": select(defined(coordinates) => coordinates{lat, lng}, farm->coordinates{lat, lng}),  "ownCoordinates": defined(coordinates),  "seasons": *[_type == "season" && field._ref == ^._id] | order(year desc){    _id, year, stage, plantingDate, expectedHarvest,    "cropName": crop->name,    "gddModelKey": crop->gddModelKey,    "growthCycleDays": crop->growthCycleDays,    "pestCount": count(*[_type == "pestReport" && season._ref == ^._id]),    "lastChange": stageHistory[-1]{stage, effectiveDate, gddTotal}  }}
export type LOAD_FARM_OVERVIEW_FIELDS_QUERY_RESULT = Array<{
  _id: string
  name: string | null
  hectares: number | null
  soilType: "chalky" | "clay" | "loamy" | "peaty" | "sandy" | "silty" | null
  colour: string | null
  photo: {
    hotspot: SanityImageHotspot | null
    crop: SanityImageCrop | null
    asset: {
      _id: string
      lqip: string | null
      dominant: string | null
    } | null
  } | null
  coordinates: {
    lat: number | null
    lng: number | null
  } | null
  ownCoordinates: false | true
  seasons: Array<{
    _id: string
    year: number | null
    stage: "growing" | "harvested" | "planning" | "planted" | "pre-harvest" | "review" | null
    plantingDate: string | null
    expectedHarvest: string | null
    cropName: string | null
    gddModelKey: "canola" | "narrow-leafed lupin" | "wheat" | null
    growthCycleDays: number | null
    pestCount: number
    lastChange: {
      stage: string | null
      effectiveDate: string | null
      gddTotal: number | null
    } | null
  }>
}>

// Source: src/lib/sanity/queries.ts
// Variable: LOAD_RECENT_ACTIVITY_SEASONS_QUERY
// Query: *[_type == "season" && count(stageHistory) > 0 && field->farm->slug.current == $slug]{  _id, year,  "cropName": crop->name,  "fieldName": field->name,  "history": stageHistory[]{stage, previousStage, effectiveDate, timestamp, basis, triggeredBy}}
export type LOAD_RECENT_ACTIVITY_SEASONS_QUERY_RESULT = Array<{
  _id: string
  year: number | null
  cropName: string | null
  fieldName: string | null
  history: Array<{
    stage: string | null
    previousStage: string | null
    effectiveDate: string | null
    timestamp: string | null
    basis: string | null
    triggeredBy: string | null
  }> | null
}>

// Source: src/lib/sanity/queries.ts
// Variable: LOAD_SEASON_QUERY
// Query: *[_type == "season" && _id == $id][0]{  _id, _rev, year, stage, plantingDate, expectedHarvest, actualHarvest, derivedMaturityDate,  yieldAmount, stageHistory, aiSummary, "notes": notes[_type == "seasonNote"] | order(createdAt desc),  "fieldName": field->name,  "fieldPhoto": field->photo{hotspot, crop, "asset": asset->{_id, "lqip": metadata.lqip, "dominant": metadata.palette.dominant.background}},  "soilReport": field->soilReport.asset->{url, originalFilename, size},  "fieldId": field._ref,  "farmSlug": field->farm->slug.current,  "benchmarkResolved": defined(crop->benchmarks.unavailableReason)    || count(*[_type == "benchmark" && crop._ref == ^.crop._ref]) > 0,  "cropId": crop._ref,  "cropName": crop->name,  "cultivar": crop->cultivar,  "gddModelKey": crop->gddModelKey,  "growthCycleDays": crop->growthCycleDays,  "unavailableReason": crop->benchmarks.unavailableReason,  "coordinates": select(defined(field->coordinates) => field->coordinates{lat, lng}, field->farm->coordinates{lat, lng}),  "benchmarks": *[_type == "benchmark" && crop._ref == ^.crop._ref] | order(source asc){    _id, source, scope, region, unit, sourceUrl, licence, observations  },  "pests": *[_type == "pestReport" && season._ref == ^._id] | order(distanceKm asc){    _id, pest, date, distanceKm, sourceUrl, scope  },  "observations": *[_type == "observation" && season._ref == ^._id] | order(date desc)[0...20]{    _id, date, notes  },  "treatments": *[_type == "treatment" && season._ref == ^._id] | order(date desc)[0...20]{    _id, date, type, product, dosage, method, applicator, notes  }}
export type LOAD_SEASON_QUERY_RESULT = {
  _id: string
  _rev: string
  year: number | null
  stage: "growing" | "harvested" | "planning" | "planted" | "pre-harvest" | "review" | null
  plantingDate: string | null
  expectedHarvest: string | null
  actualHarvest: string | null
  derivedMaturityDate: string | null
  yieldAmount: number | null
  stageHistory: Array<{
    stage?: string
    previousStage?: string
    effectiveDate?: string
    timestamp?: string
    basis?: string
    gddTotal?: number
    derivedFrom?: "gdd-model" | "plantingDate" | "regional-benchmark"
    triggeredBy?: string
    notes?: string
    weatherFetched?: boolean
    weatherSnapshotId?: string
    _type: "stageChange"
    _key: string
  }> | null
  aiSummary: {
    text?: string
    generatedAt?: string
  } | null
  notes: Array<{
    createdAt?: string
    updatedAt?: string
    author?: string
    ownerId?: string
    body?: Array<{
      children?: Array<{
        marks?: Array<string>
        text?: string
        _type: "span"
        _key: string
      }>
      style?: "normal"
      listItem?: "bullet"
      markDefs?: null
      level?: number
      _type: "block"
      _key: string
    }>
    _type: "seasonNote"
    _key: string
  }> | null
  fieldName: string | null
  fieldPhoto: {
    hotspot: SanityImageHotspot | null
    crop: SanityImageCrop | null
    asset: {
      _id: string
      lqip: string | null
      dominant: string | null
    } | null
  } | null
  soilReport: {
    url: string | null
    originalFilename: string | null
    size: number | null
  } | null
  fieldId: string | null
  farmSlug: string | null
  benchmarkResolved: boolean | true
  cropId: string | null
  cropName: string | null
  cultivar: string | null
  gddModelKey: "canola" | "narrow-leafed lupin" | "wheat" | null
  growthCycleDays: number | null
  unavailableReason: string | null
  coordinates: {
    lat: number | null
    lng: number | null
  } | null
  benchmarks: Array<{
    _id: string
    source: "harveststat" | "psd" | "worldbank" | null
    scope: "national" | "provincial" | null
    region: string | null
    unit: string | null
    sourceUrl: string | null
    licence: string | null
    observations: Array<{
      year?: number
      value?: number
      _type: "observation"
      _key: string
    }> | null
  }>
  pests: Array<{
    _id: string
    pest: string | null
    date: string | null
    distanceKm: number | null
    sourceUrl: string | null
    scope: "field" | "regional" | null
  }>
  observations: Array<{
    _id: string
    date: string | null
    notes: string | null
  }>
  treatments: Array<{
    _id: string
    date: string | null
    type: "fertiliser" | "fungicide" | "herbicide" | "irrigation" | "other" | "pesticide" | null
    product: string | null
    dosage: string | null
    method: "broadcast" | "drip" | "foliar" | "injection" | "spray" | null
    applicator: string | null
    notes: string | null
  }>
} | null

// Source: src/lib/sanity/queries.ts
// Variable: LOAD_RECOMMENDATIONS_QUERY
// Query: *[_type == "agronomyRecommendation" && field->farm->slug.current == $slug]  | order(createdAt desc)[0...$limit]{  _id, type, status, rationale, createdAt, createdBy, reviewedAt, reviewedBy, decisionNote,  "seasonId": season._ref,  "seasonLabel": season->crop->name + " " + string(season->year),  "fieldName": field->name,  "evidence": coalesce(evidence[]{kind, label, ref, detail}, [])}
export type LOAD_RECOMMENDATIONS_QUERY_RESULT = Array<{
  _id: string
  type: "custom" | "monitor" | "review_benchmark" | "review_data" | "scout_pest" | null
  status: "approved" | "completed" | "expired" | "proposed" | "rejected" | null
  rationale: string | null
  createdAt: string | null
  createdBy: string | null
  reviewedAt: string | null
  reviewedBy: string | null
  decisionNote: string | null
  seasonId: string | null
  seasonLabel: string | null
  fieldName: string | null
  evidence:
    | Array<{
        kind: string | null
        label: string | null
        ref: string | null
        detail: string | null
      }>
    | Array<never>
}>

// Source: src/lib/sanity/queries.ts
// Variable: LOAD_REGION_GRID_QUERY
// Query: *[_id == "region-grid-western-cape"][0]{  seasonStart, throughDate, archiveUpdatedAt, forecastAt, lastAttemptAt, lastError,  "cells": cells[]{lat, lng, land, gdd, tempMax, rain7}}
export type LOAD_REGION_GRID_QUERY_RESULT =
  | {
      seasonStart: null
      throughDate: null
      archiveUpdatedAt: null
      forecastAt: null
      lastAttemptAt: null
      lastError: null
      cells: null
    }
  | {
      seasonStart: string | null
      throughDate: string | null
      archiveUpdatedAt: string | null
      forecastAt: string | null
      lastAttemptAt: string | null
      lastError: string | null
      cells: Array<{
        lat: number | null
        lng: number | null
        land: boolean | null
        gdd: number | null
        tempMax: number | null
        rain7: number | null
      }> | null
    }
  | null

// Query TypeMap
declare global {
  interface SanityQueries {
    '*[_type == "farm" && defined(slug.current)] | order(name asc){\n  _id, name, "slug": slug.current, location,\n  "coordinates": coordinates{lat, lng},\n  "fieldCount": count(*[_type == "field" && farm._ref == ^._id]),\n  "hectares": math::sum(*[_type == "field" && farm._ref == ^._id].hectares),\n  "activeSeasons": count(*[_type == "season" && stage != "review" && field->farm._ref == ^._id])\n}': LOAD_FARMS_QUERY_RESULT
    '*[_type == "farm" && slug.current == $slug][0]{\n  name, "slug": slug.current, location, "coordinates": coordinates{lat, lng}\n}': LOAD_FARM_OVERVIEW_FARM_QUERY_RESULT
    '*[_type == "field" && farm->slug.current == $slug] | order(name asc){\n  _id, name, hectares, soilType, colour,\n  "photo": photo{hotspot, crop, "asset": asset->{_id, "lqip": metadata.lqip, "dominant": metadata.palette.dominant.background}},\n  "coordinates": select(defined(coordinates) => coordinates{lat, lng}, farm->coordinates{lat, lng}),\n  "ownCoordinates": defined(coordinates),\n  "seasons": *[_type == "season" && field._ref == ^._id] | order(year desc){\n    _id, year, stage, plantingDate, expectedHarvest,\n    "cropName": crop->name,\n    "gddModelKey": crop->gddModelKey,\n    "growthCycleDays": crop->growthCycleDays,\n    "pestCount": count(*[_type == "pestReport" && season._ref == ^._id]),\n    "lastChange": stageHistory[-1]{stage, effectiveDate, gddTotal}\n  }\n}': LOAD_FARM_OVERVIEW_FIELDS_QUERY_RESULT
    '*[_type == "season" && count(stageHistory) > 0 && field->farm->slug.current == $slug]{\n  _id, year,\n  "cropName": crop->name,\n  "fieldName": field->name,\n  "history": stageHistory[]{stage, previousStage, effectiveDate, timestamp, basis, triggeredBy}\n}': LOAD_RECENT_ACTIVITY_SEASONS_QUERY_RESULT
    '*[_type == "season" && _id == $id][0]{\n  _id, _rev, year, stage, plantingDate, expectedHarvest, actualHarvest, derivedMaturityDate,\n  yieldAmount, stageHistory, aiSummary, "notes": notes[_type == "seasonNote"] | order(createdAt desc),\n  "fieldName": field->name,\n  "fieldPhoto": field->photo{hotspot, crop, "asset": asset->{_id, "lqip": metadata.lqip, "dominant": metadata.palette.dominant.background}},\n  "soilReport": field->soilReport.asset->{url, originalFilename, size},\n  "fieldId": field._ref,\n  "farmSlug": field->farm->slug.current,\n  "benchmarkResolved": defined(crop->benchmarks.unavailableReason)\n    || count(*[_type == "benchmark" && crop._ref == ^.crop._ref]) > 0,\n  "cropId": crop._ref,\n  "cropName": crop->name,\n  "cultivar": crop->cultivar,\n  "gddModelKey": crop->gddModelKey,\n  "growthCycleDays": crop->growthCycleDays,\n  "unavailableReason": crop->benchmarks.unavailableReason,\n  "coordinates": select(defined(field->coordinates) => field->coordinates{lat, lng}, field->farm->coordinates{lat, lng}),\n  "benchmarks": *[_type == "benchmark" && crop._ref == ^.crop._ref] | order(source asc){\n    _id, source, scope, region, unit, sourceUrl, licence, observations\n  },\n  "pests": *[_type == "pestReport" && season._ref == ^._id] | order(distanceKm asc){\n    _id, pest, date, distanceKm, sourceUrl, scope\n  },\n  "observations": *[_type == "observation" && season._ref == ^._id] | order(date desc)[0...20]{\n    _id, date, notes\n  },\n  "treatments": *[_type == "treatment" && season._ref == ^._id] | order(date desc)[0...20]{\n    _id, date, type, product, dosage, method, applicator, notes\n  }\n}': LOAD_SEASON_QUERY_RESULT
    '*[_type == "agronomyRecommendation" && field->farm->slug.current == $slug]\n  | order(createdAt desc)[0...$limit]{\n  _id, type, status, rationale, createdAt, createdBy, reviewedAt, reviewedBy, decisionNote,\n  "seasonId": season._ref,\n  "seasonLabel": season->crop->name + " " + string(season->year),\n  "fieldName": field->name,\n  "evidence": coalesce(evidence[]{kind, label, ref, detail}, [])\n}': LOAD_RECOMMENDATIONS_QUERY_RESULT
    '*[_id == "region-grid-western-cape"][0]{\n  seasonStart, throughDate, archiveUpdatedAt, forecastAt, lastAttemptAt, lastError,\n  "cells": cells[]{lat, lng, land, gdd, tempMax, rain7}\n}': LOAD_REGION_GRID_QUERY_RESULT
  }
}
// Lets @sanity/client releases that predate the global registry read it too
declare module "@sanity/client" {
  interface SanityQueries extends globalThis.SanityQueries {}
}
